# we use java
language: java

#we use the java development kit (jdk)
jdk:
- openjdk8
services:
 #Linking Travis CI and Docker
 - docker
before_install:
 - mvn clean
 - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
 - mvn test
 - echo "$DOCKER_PASSWORD" | docker login  -u "$DOCKER_USERNAME" --password-stdin
 - docker pull openjdk:8-jdk-alpine

script:
# we avoid this error : "the job expected the maximum log length and has been terminated"
 - cat $HOME/.m2/settings.xml
 - mvn deploy