# we use java
language: java

#we use the java development kit (jdk)
jdk:
- openjdk8

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test

script:
# we avoid this error : "the job expected the maximum log length and has been terminated"
 - cat $HOME/.m2/settings.xml
